favicon: null
name: paulshipperstudio
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5171858
  brandStrength: 0.5182599
  lightness: 0.5161117
  brandColors:
    - '#37393A'
    - '#E9B488'
    - '#535B5C'
    - '#C6926E'
    - '#ABAD99'
  rhythmicContrast: 0.5150376
typography_spectrum: 0.5816327
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9199785
analytics:
  twitter: null
  google: null
  facebook: null
