favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4237379
  brandStrength: 0.8372717
  lightness: 0.2110634
  brandColors:
    - '#010101'
    - '#FCFCFB'
    - '#20B3CD'
    - '#DFAB39'
    - '#CE3003'
  rhythmicContrast: 0.6063373
typography_spectrum: 0.4044038
layout_spectrum: 0.9328679
analytics:
  twitter: null
  google: null
  facebook: null
name: paulshipperstudio
