layout_spectrum: 0.9328679
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.8356709412764758
  brandStrength: 0.8372717
  lightness: 0.01995655498467386
  brandColors:
    - '#010101'
    - '#FCFCFB'
    - '#20B3CD'
    - '#DFAB39'
    - '#CE3003'
  rhythmicContrast: 0.006529459031298757
typography_spectrum: 0.4044038
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: paulshipperstudio
