name: paulshipperstudio
favicon: null
layout_spectrum: 0.24149
typography_spectrum: 0.31566
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Paul Shipper Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#393939'
    - '#5C5C5C'
    - '#FCFCFC'
    - '#A2A2A2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
