name: paulshipperstudio
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6933405
  brandStrength: 1
  lightness: 0.556928
  brandColors:
    - '#010101'
    - '#FCFCFB'
    - '#20B3CD'
    - '#DFAB39'
    - '#CE3003'
  rhythmicContrast: 0.537594
typography_spectrum: 0.4044038
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 1
