favicon: null
name: paulshipperstudio
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0
  lightness: 0.4871106
  brandColors:
    - '#010101'
    - '#FCFCFB'
    - '#20B3CD'
    - '#DFAB39'
    - '#CE3003'
  rhythmicContrast: 0
typography_spectrum: 0.5816327
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
